name: Plugiix
version: '${project.version}'
description: 'A global plugin made for Matiix310 personal servers'
main: fr.matiix310.plugiix.Plugiix
api-version: '1.20'
author: Matiix310

##############################
#########  COMMANDS  #########
##############################

commands:
  feed:
    description: Feed the requested player
    permission: plugiix.feed
    permission-message: You don't have the permission to use this command!
    usage: /feed [pseudo]
  setfood:
    description: set the food level of the requested player
    permission: plugiix.feed
    permission-message: You don't have the permission to use this command!
    usage: /setfood [pseudo] <foodLevel>
  heal:
    description: Heal the requested player
    permission: plugiix.heal
    permission-message: You don't have the permission to use this command!
    usage: /heal [pseudo]
  sethealth:
    description: Set the health of the requested player
    permission: plugiix.heal
    permission-message: You don't have the permission to use this command!
    usage: /sethealth [pseudo] <health>
  tpa:
    description: Ask a player to teleport you at his position.
    permission: plugiix.tpa
    permission-message: You don't have the permission to use this command!
    usage: /tpa <pseudo>
  tpaccept:
    description: Accept a teleportation request from a player.
    permission: plugiix.tpa
    permission-message: You don't have the permission to use this command!
    usage: /tpaccept <pseudo>
  tpdecline:
    description: Decline a teleportation request from a player.
    permission: plugiix.tpa
    permission-message: You don't have the permission to use this command!
    usage: /tpdecline <pseudo>

##############################
#######  PERMISSIONS  ########
##############################

permissions:
  plugiix.feed:
    default: op
    description: Use the feed command
  plugiix.heal:
    default: op
    description: Use the heal command
  plugiix.tpa:
    default: true
    description: Use the tpa command.
